[package]
name = "psrepo"
version = "0.1.0-dev0"
edition = "2024"

[dependencies]
phenopackets = "0.2.2-post2"
prost = "0.14.4"
serde = {version = "1.0.229",features = ["derive", "std"]}
serde_json = "1.0.151"
uuid = {version = "1.26.1", features = ["v4", "serde"]}

[dev-dependencies]
parameterized = "2.1.0"
tempfile = "3"

[[example]]
name = "configure-phenostore"
